name: Test

on:
  push:
    branches:
      - main
    paths:
      - '**.ts'
      - '**.js'
      - '**.json'
      - '.github/workflows/test.yml'
  pull_request:
    branches:
      - main
    paths:
      - '**.ts'
      - '**.js'
      - '**.json'
      - '.github/workflows/test.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [ chromium, firefox, webkit ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: 14
      - run: npm ci
      - run: npx playwright install --with-deps ${{ matrix.browser }}
      - run: npm run test-${{ matrix.browser }}
